python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v LHE_DeltaM_mjj LHE_MothInfo_mjj gen_mjj -o Comp_mjj_ThreeDifferentMethod_Zoomed.png --xlabel "m_{jj}" --nbin 50 --xmin 0 --xmax 500
python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v LHE_DeltaM_mjj LHE_MothInfo_mjj gen_mjj -o Comp_mjj_ThreeDifferentMethod.png --xlabel "m_{jj}" --nbin 50 --xmin 0 --xmax 5000
python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v LHELeptPt gen_LeptPt -o Comp_LepPT_ThreeDifferentMethod.png --xlabel "Lepton p_{T}" --nbin 50 --xmin 0 --xmax 500
python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v LHELeptEta gen_LeptEta -o Comp_LepEta_ThreeDifferentMethod.png --xlabel "Lepton #eta" --nbin 50 --xmin 0 --xmax 500
python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v LHE_DeltaM_Iqrk0_pt LHE_MothInfo_Iqrk0_pt -o Comp_VBF1_PT_ThreeDifferentMethod.png --xlabel "VBF1 p_{T}" --nbin 50 --xmin 0 --xmax 500
python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v LHE_DeltaM_Iqrk1_pt LHE_MothInfo_Iqrk1_pt -o Comp_VBF2_PT_ThreeDifferentMethod.png --xlabel "VBF2 p_{T}" --nbin 50 --xmin 0 --xmax 500
python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v LHE_DeltaM_mWW LHE_MothInfo_mWW gen_mWW -o Comp_mWW_ThreeDifferentMethod_Zoomed.png --xlabel "m (WW)" --nbin 50 --xmin 0 --xmax 500
python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v LHE_DeltaM_mtWW LHE_MothInfo_mtWW gen_mtWW -o Comp_mtWW_ThreeDifferentMethod_Zoomed.png --xlabel "mT (WW)" --nbin 50 --xmin 0 --xmax 500
#python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v   -o Comp_mWW_ThreeDifferentMethod.png --xlabel "mWW" --nbin 50 --xmin 0 --xmax 500
#python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v  -o Comp_mWW_ThreeDifferentMethod.png --xlabel "mWW" --nbin 50 --xmin 0 --xmax 500
#python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v  -o Comp_mWW_ThreeDifferentMethod.png --xlabel "mWW" --nbin 50 --xmin 0 --xmax 500
#python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v  -o Comp_mWW_ThreeDifferentMethod.png --xlabel "mWW" --nbin 50 --xmin 0 --xmax 500
#python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v  -o Comp_mWW_ThreeDifferentMethod.png --xlabel "mWW" --nbin 50 --xmin 0 --xmax 500
#python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v  -o Comp_mWW_ThreeDifferentMethod.png --xlabel "mWW" --nbin 50 --xmin 0 --xmax 500
#python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v  -o Comp_mWW_ThreeDifferentMethod.png --xlabel "mWW" --nbin 50 --xmin 0 --xmax 500
#python make_CompHistoFromSameRootFile.py -n /uscms_data/d3/rasharma/aQGC_analysis/AnalysisFramework/GENAnalyzer/LHEonlyGEN/CMSSW_8_0_11/src/GEN-SIM-analyzer/GenAnalyzer/LHEinfo.root --logy --grid -v  -o Comp_mWW_ThreeDifferentMethod.png --xlabel "mWW" --nbin 50 --xmin 0 --xmax 500
