#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk0_pt --xmin 0.0 --xmax 1500 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk0_eta --xmin -5.0 --xmax 5.0 --nbin 20
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk0_phi --xmin -4.0 --xmax 4.0 --nbin 20
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk0_M --xmin 0.0 --xmax 150 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk0_E --xmin 0.0 --xmax 1500 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk0_Mt --xmin 0.0 --xmax 1500 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk1_pt --xmin 0.0 --xmax 1500 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk1_eta --xmin -5.0 --xmax 5.0 --nbin 20
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk1_phi --xmin -4.0 --xmax 4.0 --nbin 20
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk1_M --xmin 0.0 --xmax 150 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Wqrk1_E --xmin 0.0 --xmax 1500 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk1_Mt --xmin 0.0 --xmax 1500 --nbin 25
############################################################
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk0_pt --xmin 0.0 --xmax 1500 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk0_eta --xmin -5.0 --xmax 5.0 --nbin 20
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk0_phi --xmin -4.0 --xmax 4.0 --nbin 20
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk0_M --xmin 0.0 --xmax 150 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk0_E --xmin 0.0 --xmax 1500 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk0_Mt --xmin 0.0 --xmax 1500 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk1_pt --xmin 0.0 --xmax 1500 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk1_eta --xmin -5.0 --xmax 5.0 --nbin 20
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk1_phi --xmin -4.0 --xmax 4.0 --nbin 20
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk1_M --xmin 0.0 --xmax 150 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk1_E --xmin 0.0 --xmax 1500 --nbin 25
#python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_Iqrk1_Mt --xmin 0.0 --xmax 1500 --nbin 25
#######################################################################3
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_mWW --xmin 0.0 --xmax 2500 --nbin 25
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_mtWW --xmin 0.0 --xmax 2500 --nbin 25
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_mWLep --xmin 40.0 --xmax 150 --nbin 25
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_mtWLep --xmin 0.0 --xmax 1500 --nbin 25
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_mWHad --xmin 40.0 --xmax 120 --nbin 25
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_mtWHad --xmin 0.0 --xmax 1500 --nbin 25
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_mjj --xmin 0.0 --xmax 3500 --nbin 25
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_costheta1 --xmin -1.2 --xmax 1.2 --nbin 20
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_costheta2 --xmin -1.2 --xmax 1.2 --nbin 20
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_phi --xmin -4.0 --xmax 4.0 --nbin 20
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_costhetastar --xmin -1.2 --xmax 1.2 --nbin 20
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_phi1 --xmin -4.0 --xmax 4.0 --nbin 20
 compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_dEtajj --xmin 0.0 --xmax 11.0 --nbin 20
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_dPhijj --xmin -3.5 --xmax 3.5 --nbin 20
python compare_SM_with_RwgtSM_DiffPars_MiniAOD_Gen_Sample.py -v LHE_MothInfo_VBSCentrality --xmin -0.0 --xmax 15.0 --nbin 20
